CREATE TABLE IF NOT EXISTS streaks (
  id SERIAL PRIMARY KEY,
  habit_id INTEGER NOT NULL UNIQUE REFERENCES habits (id) ON DELETE CASCADE,
  current_streak INTEGER NOT NULL DEFAULT 0,
  best_streak INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
